# Site settings
title: ZWS
email: hi@zachsorenson.com
description: > # this means to ignore newlines until "baseurl:"
  Harvard Law student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zachsorenson.com" # the base hostname & protocol for your site
twitter_username: zwsorenson
github_username:  zwsorenson
linkedin_username: zwsorenson
# Build settings
markdown: kramdown
highlighter: rouge
