# Site settings
title: Zach Sorenson
email: me@zachsorenson.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.zachsorenson.com" # the base hostname & protocol for your site
twitter_username: zwsorenson
github_username:  zwsorenson

# Build settings
markdown: kramdown
