# Site settings
title: Zach Sorenson
email: me@zachsorenson.com
description: > # this means to ignore newlines until "baseurl:"
  Zach's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.zachsorenson.com" # the base hostname & protocol for your site
twitter_username: zwsorenson
github_username:  zwsorenson

# Build settings
markdown: kramdown
